### ISSUE TITLE
Cannot connect password key to user as admin

### ISSUE THREAD

**Issue by stemid** [sii/siptrackweb#12]
A common issue I've run into is that administrators cannot connect password keys to users. 

It only works once the user logs in and connects it themselves. This is not a good solution as it requires handing out the password key password to the user. Or logging in as that user. 

Will need to troubleshoot this when time is given.

**Comment by sii** [comment]
Is it for new user accounts? A user has to have logged in at least once before an admin can connect a password key to their user account.

**Comment by stemid** [comment]
No not for new user accounts. As part of troubleshooting I've asked users to logout and log back in. All that happens then is that the pending subkey disappears from the list of children on the user.

**Comment by sii** [comment]
Hm, I'm unable to reproduce the problem. Does it happen every time or only sometimes? Let me know if there is anything I can do to help.

**Comment by stemid** [comment]
I'm going to close this because I haven't had any complaints in a long time.
