### ISSUE TITLE
Possibility to show active directory passwords on tagged servers

### ISSUE THREAD

**Issue by robinostlund** [sii/siptrackweb#20]
If a device with class active directory is linked to a server then it would be good if the passwords from the active directory is shown on the server. Also open for other solutions :)

**Comment by stemid** [comment]
I think this should probably be solved with some automation, and not edits to the code. 

I would suggest a script that goes through a certain path of Siptrack, recursively, and for each attribute called active directory it could create a device link. 

Of course this requires first of all that passwords can be linked to other devices. I'm not sure if that's possible yet.

**Comment by stemid** [comment]
After some thought I think we should first make passwords and password categories linkable to devices. 

Then users can themselves link an Active Directory password category, or a single password, to the relevant devices. 

This is in fact much better imo than adding passwords directly under devices as child nodes. 

I'm closing this issue and opening a new one for the ability to link password categories and passwords to devices instead. #22
